model: tgn
node_feat_dim: 64
edge_feat_dim: 32
memory_dim: 100
time_dim: 100
embedding_dim: 100
n_heads: 2
n_layers: 1
dropout: 0.1
num_nodes: 500000
batch_size: 200
neighbor_size: 10
lr: 1.0e-4
max_epochs: 50
data_dir: data/graph
